import { NewTool } from "../schema.js";

export const initialToolsData: NewTool[] = [
  // --- All-in-One HRIS & Core HR ---
  {
    id: "personio",
    name: "Personio",
    slug: "personio",
    category: "hris",
    categoryLabel: "All-in-One HRIS",
    shortDescription: "Europe's leading all-in-one HR software for SMEs from 10 to 2,000 employees.",
    fullDescription: "Personio digitizes core HR, recruiting, onboarding, and payroll management with market-leading DATEV integrations and BAG-compliant time tracking.",
    websiteUrl: "https://www.personio.com",
    logoUrl: "/tools/personio.svg",
    minTeamSize: 10,
    maxTeamSize: 2000,
    badge: "Best Overall for DACH SMEs",
    pricingTier: "growth",
    regions: ["region_dach", "region_uk_europe"],
    features: [
      "core_digital_records",
      "core_onboarding",
      "core_compliance",
      "core_signatures",
      "core_org_charts",
      "payroll_datev",
      "payroll_local_eu",
      "ats_multiposting",
      "ats_structured_hiring",
      "time_bag_compliant",
      "time_absence",
      "int_datev",
      "int_slack_teams",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_datev", "int_slack_teams", "int_sso", "int_api"],
    strengths: ["Flawless DATEV integration", "German compliance & GDPR standard", "All-in-one convenience"],
    limitations: ["Less specialized for complex global enterprise multi-entities"],
    isActive: true,
  },
  {
    id: "deel",
    name: "Deel",
    slug: "deel",
    category: "payroll_eor",
    categoryLabel: "Global HR & Payroll",
    shortDescription: "Global payroll, compliance, and Employer of Record (EOR) in 150+ countries.",
    fullDescription: "Deel simplifies international hiring, contractor invoicing, multi-currency payouts, and compliance across distributed workforces.",
    websiteUrl: "https://www.deel.com",
    logoUrl: "/tools/deel.svg",
    minTeamSize: 1,
    maxTeamSize: 10000,
    badge: "Best for Global Distributed Teams",
    pricingTier: "growth",
    regions: ["region_global", "region_uk_europe", "region_north_america", "region_dach", "region_mena"],
    features: [
      "core_digital_records",
      "core_onboarding",
      "core_signatures",
      "payroll_global_eor",
      "payroll_local_eu",
      "time_absence",
      "int_slack_teams",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_sso", "int_api"],
    strengths: ["150+ country compliance", "Contractor & EOR mastery", "Multi-currency processing"],
    limitations: ["More focused on distributed hiring than local German chamber requirements"],
    isActive: true,
  },
  {
    id: "factorial",
    name: "Factorial",
    slug: "factorial",
    category: "hris",
    categoryLabel: "All-in-One HR & Ops",
    shortDescription: "Intuitive all-in-one HR platform for fast-growing small and medium businesses.",
    fullDescription: "Factorial automates time management, expenses, applicant tracking, performance reviews, and document management with a modern user experience.",
    websiteUrl: "https://factorialhr.com",
    logoUrl: "/tools/factorial.svg",
    minTeamSize: 5,
    maxTeamSize: 1000,
    badge: "High Usability for Growing Teams",
    pricingTier: "starter",
    regions: ["region_dach", "region_uk_europe", "region_global"],
    features: [
      "core_digital_records",
      "core_onboarding",
      "core_signatures",
      "payroll_local_eu",
      "time_bag_compliant",
      "time_absence",
      "time_shift_planning",
      "perf_360_reviews",
      "int_slack_teams",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_api"],
    strengths: ["Fast onboarding", "Excellent shift & absence planning", "Cost effective"],
    limitations: ["Less deep on complex enterprise salary matrixing"],
    isActive: true,
  },
  {
    id: "rippling",
    name: "Rippling",
    slug: "rippling",
    category: "hris",
    categoryLabel: "Unified Workforce & IT Platform",
    shortDescription: "Unifies HR, Global Payroll, and Employee IT hardware/app provisioning in one platform.",
    fullDescription: "Rippling automates employee lifecycle management alongside IT device management, identity access, and global payroll.",
    websiteUrl: "https://www.rippling.com",
    logoUrl: "/tools/rippling.svg",
    minTeamSize: 20,
    maxTeamSize: 5000,
    badge: "Best for Tech & IT-Heavy Scaleups",
    pricingTier: "enterprise",
    regions: ["region_global", "region_north_america", "region_uk_europe"],
    features: [
      "core_digital_records",
      "core_onboarding",
      "core_signatures",
      "core_org_charts",
      "payroll_global_eor",
      "payroll_local_eu",
      "time_bag_compliant",
      "time_absence",
      "int_slack_teams",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_sso", "int_api"],
    strengths: ["Unrivaled IT app & hardware automation", "Deep workflow builder", "Global scalability"],
    limitations: ["Higher price point", "Complex setup"],
    isActive: true,
  },
  {
    id: "flair",
    name: "Flair",
    slug: "flair",
    category: "hris",
    categoryLabel: "Salesforce-Native HR",
    shortDescription: "Enterprise-grade HR suite built natively on Salesforce infrastructure.",
    fullDescription: "Flair provides deep customization, shift planning, recruiting, and employee hub built directly on the Salesforce CRM cloud.",
    websiteUrl: "https://flair.hr",
    logoUrl: "/tools/flair.svg",
    minTeamSize: 50,
    maxTeamSize: 5000,
    badge: "Best for Salesforce Ecosystems",
    pricingTier: "enterprise",
    regions: ["region_dach", "region_uk_europe", "region_global"],
    features: [
      "core_digital_records",
      "core_onboarding",
      "core_org_charts",
      "payroll_datev",
      "time_bag_compliant",
      "time_shift_planning",
      "int_datev",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_datev", "int_sso", "int_api"],
    strengths: ["100% Salesforce native", "Enterprise permissions", "Custom reporting"],
    limitations: ["Requires Salesforce familiarity"],
    isActive: true,
  },

  // --- Specialized Recruiting & ATS ---
  {
    id: "greenhouse",
    name: "Greenhouse",
    slug: "greenhouse",
    category: "recruiting",
    categoryLabel: "Enterprise ATS & Hiring OS",
    shortDescription: "The hiring operating system for structured hiring, talent pipelines, and DE&I analytics.",
    fullDescription: "Greenhouse provides comprehensive interview kits, scorecards, structured hiring workflows, and deep candidate analytics for scaling organizations.",
    websiteUrl: "https://www.greenhouse.com",
    logoUrl: "/tools/greenhouse.svg",
    minTeamSize: 50,
    maxTeamSize: 10000,
    badge: "Benchmark for Structured Hiring",
    pricingTier: "enterprise",
    regions: ["region_global", "region_north_america", "region_uk_europe", "region_dach"],
    features: [
      "ats_multiposting",
      "ats_structured_hiring",
      "ats_candidate_experience",
      "ats_talent_pool",
      "ats_advanced_analytics",
      "int_slack_teams",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_sso", "int_api"],
    strengths: ["Best-in-class scorecards", "Rigorous structured interview kits", "Huge partner ecosystem"],
    limitations: ["Enterprise cost", "Dedicated recruiter admin required"],
    isActive: true,
  },
  {
    id: "ashby",
    name: "Ashby",
    slug: "ashby",
    category: "recruiting",
    categoryLabel: "Next-Gen All-in-One Recruiting",
    shortDescription: "High-performance recruiting platform combining ATS, CRM sourcing, self-scheduling, and deep analytics.",
    fullDescription: "Ashby eliminates fragmented recruiting tools by combining candidate sourcing, automated scheduling, structured interviews, and real-time pipeline BI.",
    websiteUrl: "https://www.ashbyhq.com",
    logoUrl: "/tools/ashby.svg",
    minTeamSize: 20,
    maxTeamSize: 5000,
    badge: "Top Choice for High-Growth Tech",
    pricingTier: "growth",
    regions: ["region_global", "region_uk_europe", "region_north_america", "region_dach"],
    features: [
      "ats_multiposting",
      "ats_structured_hiring",
      "ats_candidate_experience",
      "ats_talent_pool",
      "ats_advanced_analytics",
      "int_slack_teams",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_sso", "int_api"],
    strengths: ["Ultra-fast UI", "Built-in candidate self-scheduling", "Unmatched recruitment analytics"],
    limitations: ["Premium pricing for early-stage startups"],
    isActive: true,
  },
  {
    id: "teamtailor",
    name: "Teamtailor",
    slug: "teamtailor",
    category: "recruiting",
    categoryLabel: "Employer Branding & ATS",
    shortDescription: "Recruiting software with best-in-class career site builder and candidate experience.",
    fullDescription: "Teamtailor empowers companies to attract candidates through interactive career pages, automated candidate messaging, and collaborative hiring pipelines.",
    websiteUrl: "https://www.teamtailor.com",
    logoUrl: "/tools/teamtailor.svg",
    minTeamSize: 10,
    maxTeamSize: 2000,
    badge: "Best for Employer Branding",
    pricingTier: "growth",
    regions: ["region_dach", "region_uk_europe", "region_global"],
    features: [
      "ats_multiposting",
      "ats_candidate_experience",
      "ats_talent_pool",
      "int_slack_teams",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_api"],
    strengths: ["Beautiful drag-and-drop career page builder", "Great candidate experience", "Quick adoption"],
    limitations: ["Less complex scorecard custom algorithms than Greenhouse"],
    isActive: true,
  },
  {
    id: "d-vinci",
    name: "D.vinci",
    slug: "d-vinci",
    category: "recruiting",
    categoryLabel: "German Enterprise ATS",
    shortDescription: "Secure German applicant tracking system tailored for DACH compliance and enterprise hiring.",
    fullDescription: "D.vinci offers extensive multiposting, works council (Betriebsrat) integration workflows, and strict German data privacy standards.",
    websiteUrl: "https://www.d-vinci.de",
    logoUrl: "/tools/d-vinci.svg",
    minTeamSize: 50,
    maxTeamSize: 10000,
    badge: "Best for German Works Council Compliance",
    pricingTier: "enterprise",
    regions: ["region_dach"],
    features: [
      "ats_multiposting",
      "ats_structured_hiring",
      "ats_talent_pool",
      "core_compliance",
      "int_api"
    ],
    integrations: ["int_api"],
    strengths: ["Works council approval flows", "Strict German hosting & legal compliance", "Enterprise stability"],
    limitations: ["Traditional interface"],
    isActive: true,
  },

  // --- Specialized Performance & Enablement ---
  {
    id: "leapsome",
    name: "Leapsome",
    slug: "leapsome",
    category: "performance",
    categoryLabel: "People Enablement & OKRs",
    shortDescription: "The all-in-one platform for performance reviews, employee engagement, goals & OKRs, and 1:1 meetings.",
    fullDescription: "Leapsome bridges continuous feedback, 360-degree reviews, competency frameworks, salary reviews, and employee engagement surveys.",
    websiteUrl: "https://www.leapsome.com",
    logoUrl: "/tools/leapsome.svg",
    minTeamSize: 20,
    maxTeamSize: 5000,
    badge: "Top Choice for Performance & OKRs",
    pricingTier: "growth",
    regions: ["region_dach", "region_uk_europe", "region_global", "region_north_america"],
    features: [
      "perf_360_reviews",
      "perf_okrs",
      "perf_continuous_1on1",
      "perf_compensation",
      "int_slack_teams",
      "int_sso",
      "int_api"
    ],
    integrations: ["int_slack_teams", "int_sso", "int_api"],
    strengths: ["Outstanding 360° reviews & OKRs", "Competency frameworks", "Strong integrations with Personio/Slack"],
    limitations: ["Focused on performance and engagement rather than core payroll"],
    isActive: true,
  },
  {
    id: "gradar",
    name: "Gradar",
    slug: "gradar",
    category: "performance",
    categoryLabel: "Job Evaluation & Compensation",
    shortDescription: "Non-proprietary job evaluation and compensation structure grading system.",
    fullDescription: "Gradar enables transparent job leveling, salary benchmarking, gender pay gap analysis, and compensation architecture design.",
    websiteUrl: "https://gradar.com",
    logoUrl: "/tools/gradar.svg",
    minTeamSize: 50,
    maxTeamSize: 10000,
    badge: "Specialist for Job Grading & Pay Transparency",
    pricingTier: "growth",
    regions: ["region_dach", "region_uk_europe", "region_global"],
    features: [
      "perf_compensation",
      "core_compliance",
      "int_api"
    ],
    integrations: ["int_api"],
    strengths: ["EU Pay Transparency directive ready", "Scientific job grading", "Transparent compensation structure"],
    limitations: ["Specialized for job leveling, not an everyday employee portal"],
    isActive: true,
  },

  // --- Time Tracking, Global EOR & Specialized ---
  {
    id: "workmotion",
    name: "Workmotion",
    slug: "workmotion",
    category: "payroll_eor",
    categoryLabel: "European-Centric Global Talent Platform",
    shortDescription: "Berlin-based global employment platform for hiring across borders compliant with European standards.",
    fullDescription: "Workmotion helps companies onboard talent in 160+ countries with direct European support and compliant contractor/EOR frameworks.",
    websiteUrl: "https://workmotion.com",
    logoUrl: "/tools/workmotion.svg",
    minTeamSize: 5,
    maxTeamSize: 5000,
    badge: "European Leader for Global Hiring",
    pricingTier: "growth",
    regions: ["region_dach", "region_uk_europe", "region_global"],
    features: [
      "payroll_global_eor",
      "core_compliance",
      "core_signatures",
      "core_onboarding",
      "int_api"
    ],
    integrations: ["int_api"],
    strengths: ["European compliance perspective", "Fast onboarding across EU", "Direct support"],
    limitations: ["Focused on EOR & contractor onboarding"],
    isActive: true,
  },
  {
    id: "zep",
    name: "ZEP",
    slug: "zep",
    category: "time_tracking",
    categoryLabel: "Project Time Tracking & Billing",
    shortDescription: "Project time recording, travel expense management, and project billing for consultancies and service firms.",
    fullDescription: "ZEP is the standard solution for German service providers requiring precise project-based billable hours, travel expense claims, and client invoicing.",
    websiteUrl: "https://www.zep.de",
    logoUrl: "/tools/zep.svg",
    minTeamSize: 5,
    maxTeamSize: 1000,
    badge: "Best for Project Time & Client Billing",
    pricingTier: "starter",
    regions: ["region_dach"],
    features: [
      "time_bag_compliant",
      "time_absence",
      "time_project_billing",
      "int_datev",
      "int_api"
    ],
    integrations: ["int_datev", "int_api"],
    strengths: ["German project accounting", "Reisekostenabrechnung compliant with German tax laws", "DATEV billing export"],
    limitations: ["Traditional agency UI"],
    isActive: true,
  },
  {
    id: "bayzat",
    name: "Bayzat",
    slug: "bayzat",
    category: "hris",
    categoryLabel: "MENA Regional HR & Benefits",
    shortDescription: "The leading work-life platform for employee management and health insurance in the MENA region.",
    fullDescription: "Bayzat digitizes UAE/GCC labor law compliance, automated WPS payroll processing, and employee medical insurance.",
    websiteUrl: "https://www.bayzat.com",
    logoUrl: "/tools/bayzat.svg",
    minTeamSize: 10,
    maxTeamSize: 2000,
    badge: "Best for UAE & MENA Region",
    pricingTier: "growth",
    regions: ["region_mena"],
    features: [
      "core_digital_records",
      "core_onboarding",
      "payroll_local_eu",
      "time_bag_compliant",
      "time_absence",
      "int_api"
    ],
    integrations: ["int_api"],
    strengths: ["UAE WPS compliant payroll", "Local health insurance integration", "Arabic/English support"],
    limitations: ["Tailored specifically for MENA region"],
    isActive: true,
  }
];
